function [DATE,LATITUDE,LONGITUDE,CURRENT_DIRECTION,CURRENT_SPEED] = importa_derivador(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [DATE,LATITUDE,LONGITUDE,CURRENT_DIRECTION,CURRENT_SPEED] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [DATE,LATITUDE,LONGITUDE,CURRENT_DIRECTION,CURRENT_SPEED] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [DATE,LATITUDE,LONGITUDE,CURRENT_DIRECTION,CURRENT_SPEED] =
%   importfile('10032016193502_Geison Mendes_Barra pequena - vento
%   gradiente - vazante   11h e 30min - 10-03-16.txt',10, 793);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/03/11 11:16:11

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 10;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
DATE = dataArray{:, 1};
LATITUDE = dataArray{:, 2};
LONGITUDE = dataArray{:, 3};
CURRENT_DIRECTION = dataArray{:, 4};
CURRENT_SPEED = dataArray{:, 5};

